apiVersion: apps/v1
kind: Deployment
metadata:
  name: oficina-app-deployment
  namespace: oficina-mecanica
  labels:
    app: oficina-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oficina-app
  template:
    metadata:
      labels:
        app: oficina-app
    spec:
      containers:
        - name: oficina-app
          image: guribeiro/oficina-app:latest
          imagePullPolicy: Always 
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: oficina-config
            - secretRef:
                name: oficina-secret # Injeta todas as variáveis de ambiente sensíveis (ex: DATABASE_URL, JWT_SECRET)
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: oficina-service
  namespace: oficina-mecanica 
spec:
  type: NodePort # Mantido para acesso fácil no Kind
  selector:
    app: oficina-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000 # Porta fixa para localhost:30000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: oficina-app-hpa
  namespace: oficina-mecanica 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: oficina-app-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80