apiVersion: v1
kind: Secret
metadata:
  name: oficina-secret
type: Opaque
data:
  # Base64 para: postgresql://postgres:postgres@postgres-service:5432/oficina_db?schema=public
  DATABASE_URL: "cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9vZmljaW5hX2RiP3NjaGVtYT1wdWJsaWM="