apiVersion: batch/v1
kind: Job
metadata:
  name: oficina-prisma-migrate
  namespace: oficina-mecanica
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: prisma-migration
          image: __IMAGE_URI__
          command: ["sh", "-c", "npx prisma migrate deploy"]
          envFrom:
            - secretRef:
                name: oficina-app-secret